<a href="https://colab.research.google.com/github/Hendridaffa/PCVK_Genap_21-22/blob/main/Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **# Tugas Challenge**
 **1. Perkalian Matriks**

In [41]:
mat1 = [
    [2, 0, 6],
    [4, 6, 5],
    [1, 5, 3],
]

mat2 = [
    [3, 0, 3],
    [5, 2, 2],
    [6, 1, 8],]

mat3 = []

for x in range(0, len(mat1)):
    row = []
    for y in range(0, len(mat1[0])):
        total = 0
        for z in range(0, len(mat1)):
            total = total + (mat1[x][z] * mat2[z][y])
        row.append(total)
    mat3.append(row)


for x in range(0, len(mat3)):
    for y in range(0, len(mat3[0])):
        print (mat3[x][y], end=' ')
    print ()

42 6 54 
72 17 64 
46 13 37 


In [36]:
print ('Program perkalian matriks [A]*[B]=[C]')

from numpy import *
A = array([[1, 2, 4],\
           [3, 3, 2]]) # A berukuran 2x3
B = array([[1, 4],\
           [4, 3],\
           [2, 5]]) # B berukuran 3x2
n=2 # jumlah baris matrik A
m=2 # jumlah kolom matrik B
p=3 # jumlah kolom matrik A sekaligus jumlah baris matrik B
C = zeros((n,m))
for i in range(0,n):
    for j in range(0,m):
        for k in range(0,p):
            C[i][j]=C[i][j]+A[i][k]*B[k][j]

print ()
print ('matriks A')
print (A)
print ()
print ('matriks B')
print (B)
print ()
print ('matriks C (Hasil)')
print (C)

Program perkalian matriks [A]*[B]=[C]

matriks A
[[1 2 4]
 [3 3 2]]

matriks B
[[1 4]
 [4 3]
 [2 5]]

matriks C (Hasil)
[[17. 30.]
 [19. 31.]]
